### PR TITLE
Make the code Black compliant

### PR DESCRIPTION
**Pull request by HeMan**
- Make the code Black compliant
- Make tox linting step use flake8-black.

### CODE REVIEW

**Comment by nickw444** [comment]
@gmacon are you thinking of having two PRs to do that? For what it's worth the default merge strategy of this repo is to squash and merge so that history would be lost once merged into master anyway - might not be worth the additional effort and merging as a single atomic unit might make more sense (just my 2c).

**Comment by gmacon** [comment]
I hadn't actually noticed that this repo uses squash merges. I won't debate the merits of various merging strategies here.

I think this should be two PRs: one applying black and one fixing the problems we discovered. I don't want that problem fix to become lost in the single commit that changes the whole repo.

**Comment by nickw444** [comment]
I have re-enabled merge commits for the repo 👍

**Comment by HeMan** [comment]
@gmacon That makes sense! I'll do a new pull request with just the Black compliance and another with the fix.

**Comment by HeMan** [comment]
New PR is #81

**Comment by gmacon** [comment]
I think this PR was superseded by #81, so I'm closing it. Please speak up if you think that's incorrect.

**Pull request closed without merging**
