### PR TITLE
Fix pipeline

### PR DESCRIPTION
**Pull request by m-bach**
Based on the changes in #116, this should fix the lint and build-docs steps.

### CODE REVIEW

**Comment by nickw444** [comment]
Trying to figure out how to make GH run the actions workflow on this 🙈

**Comment by nickw444** [comment]
Yolo, I suppose.

**Comment by nickw444** [comment]
OK edit: Looks like it's still failing 🤦

**Comment by m-bach** [comment]
Weird it fails the tests now. Even though your changes passed the tests.
I will look into it when I've got a minute.

**Pull request merged**
