### PR TITLE
Additional TLS options

### PR DESCRIPTION
**Pull request by mwielgoszewski**
I closed out the previous PR (#11), and opened this one with your suggestions which now supports adding a server with a custom TLS context on a per-server basis.

### CODE REVIEW

**Comment by nickw444** [comment]
Hey @mwielgoszewski this looks great! Thanks for the pull, happy to merge once the following is taken care of:

Would it be possible for you to document the new configuration option `LDAP_ADD_SERVER`, just to explain what it does (i.e. stops the default server being added, the user will have to manually add the server using the `add_server` method)

Additionally, it would be great if you could add a section to the docs to document using a server with a custom TLS context. Just a line about the use-case and a code example will be fine :) 

I also noticed that the build is failing on Travis due to it failing linting with flake8.

Cheers 👍

**Comment by mwielgoszewski** [comment]
@nickw444 this has been done in 3f56770. Not sure why flake8 lint is failing.

**Comment by nickw444** [comment]
Looks like an issue in a file you didn't touch due to flake8 picking up new rules or something (I've seen this in some of my other projects).

```
$ flake8 .
./ldap_app.py:132:1: E305 expected 2 blank lines after class or function definition, found 1
```

I'll look after this once this is merged.

Just one more thing as I mentioned above, it would be good if you could add a short paragraph to the docs with the title *Custom TLS Context*, and just explain how you should use LDAP_ADD_SERVER=False and call add_server() with the user's own context.

**Comment by mwielgoszewski** [comment]
@nickw444 I tried rebasing off master but couldn't figure out how to do this cleanly.

**Comment by nickw444** [comment]
How did you go about rebasing? 

```sh
# Make a backup
git branch before-rebase-backup
# Go back to master
git checkout master
# Add upstream git origin
git remote add upstream https://github.com/nickw444/flask-ldap3-login.git
# Fetch all refs from upstream repo
git fetch upstream
# Rebase on top of upstream's master branch.
git rebase upstream/master
##~~~Check everything looks OK - The force push will overwrite your master branch on your github repo~~~
git push origin master --force
```

**Comment by mwielgoszewski** [comment]
Hey @nickw444, anything else you want me to do here?

**Comment by nickw444** [comment]
Changes look great! Sorry to be a massive pain, but it'd be great if you could drop in some tests:

```python
@mock.patch('ldap3.ServerPool', new=ServerPool)
@mock.patch('ldap3.Server', new=Server)
@mock.patch('ldap3.Connection', new=Connection)
class LDAPAddServerConfigTestCase(BaseTestCase):
    """Tests for the `LDAP_ADD_SERVER` config key"""

    <You'll need to inspect the server pool attribute, which will involve implementing mocktypes.ServerPool to allow inspection of associated servers - i.e. override the ServerPool.add() and track it in the mock)

    def setUp(self):
        ...

    def test_server_added_when_unset(self):
        """
        Ensures a default server is added when `LDAP_ADD_SERVER` is not set.
        """
        ...

    def test_server_added_when_true(self):
        """
        Ensures a default server is added when `LDAP_ADD_SERVER` is True.
        """
        ...

    def test_server_added_when_false(self):
        """
        Ensures no server is added when `LDAP_ADD_SERVER` is False.
        """
        ...

@mock.patch('ldap3.ServerPool', new=ServerPool)
@mock.patch('ldap3.Server', new=Server)
@mock.patch('ldap3.Connection', new=Connection)
class AddServerTestCase(BaseTestCase):
    """
    Tests for the `add_server` method.
    """

    <probably need to implement the constructor for mocktypes.Server, and use a similar inspection to the above testcase.>

    def setUp(self):
        ...

    def test_error_on_use_ssl_and_tls_ctx(self):
        """
        Ensures a ValueError is thrown when use_ssl is False and a TLS context
        is passed together.
        """
        ...

    def test_server_with_no_tls_ctx(self):
        """
        Ensures a server is created/added to the pool, however that the server
        was instantiated with `tls=None` and  use_ssl=False
        """
        ...

    def test_server_with_no_tls_with_ssl(self):
        """
        Ensures a server is created/added to the pool, however that the server
        was instantiated with `tls=None` and use_ssl=True.
        """
        ...

    def test_server_with_tls_with_ssl(self):
        """
        Ensures a server is created/added to the pool, however that the server
        was instantiated with `tls=<TLS CTX OBJECT>` and use_ssl=True.
        """

```

I really, really want to get this feature into this library, so let me know if you have any questions around testing!

**Comment by nickw444** [comment]
Inroads being made in https://github.com/nickw444/flask-ldap3-login/pull/23

**Pull request closed without merging**
