### PR TITLE
Add exception to Response (#91)

### PR DESCRIPTION
**Pull request by Oisins**

### CODE REVIEW

**Review by gmacon — CHANGES_REQUESTED** [review]
This seems reasonable, but I think we should change every place where a failure-status AuthenticationResponse is created from an exception, not just this one.

**Comment by Oisins** [comment]
I added the parameter to the other places. Is the style ok?

**Review by gmacon — APPROVED** [review]
OK, LGTM. Thanks!

**Comment by Oisins** [comment]
> OK, LGTM. Thanks!

Cool. Glad to help. When do you think you will release to pypi?

**Comment by gmacon** [comment]
There are some things on the todo list for 1.0: https://github.com/nickw444/flask-ldap3-login/milestone/1. @nickw444 is the only person with PyPI credentials right now, as far as I know.

**Comment by nickw444** [comment]
I think they are actually baked into the build pipeline - so pushing a tag should release a build to pypi via Travis.

**Pull request merged**
