### PR TITLE
Additional TLS options

### PR DESCRIPTION
**Pull request by mwielgoszewski**
This PR introduces several additional configuration options that allows one to configure:
- a Certificate Authority certificate file used to validate the remote LDAP server's certificate
- a client certificate and private key used for TLS client authentication to a remote LDAP server
- what level of TLS certificate validation is performed by the client when connecting to a remote LDAP server
- the TLS protocol version to use when establishing a TLS connection to a remote LDAP server
- the hostnames also accepted provided the certificate common name and subject alternative names do not match

### CODE REVIEW

**Comment by nickw444** [comment]
Thanks for the pull. I'll take a closer look this weekend and hopefully merge it! 

Cheers

**Comment by mwielgoszewski** [comment]
@nickw444 Any update? Let me know if there's anything you would prefer to see changed.

**Comment by nickw444** [comment]
@mwielgoszewski Sorry about this. I haven't yet had a change to try this out, but I will put it to the top of my list for this weekend! Been pretty busy lately 😸

**Comment by nickw444** [comment]
Hey @mwielgoszewski Just looking at this now, and I feel like the existing codebase puts us in an awkward position with this change. I really do believe that the server should be configurable, however, we need to keep in mind that different servers in the pool may have different configuration, ie, different certificates, etc. 

I'm thinking something along the lines of:

- Add an additional configuration key for `LDAP_ADD_SERVER`, defaults to `True`, and if set to `False`, `self.add_server` is not called from within `init_config`.  This will allow users to specify their own server later.
- Modify `add_server` to accept a new argument `tls_ctx=None` (to not break existing usages), which if defined, will be used as this server's TLS context. If tls_ctx is specified and use_ssl is False, then we should raise a `ValueError` since this combination doesn't make sense.

What are your thoughts on this? For your usecase, this simply means you invoking ldap.add_server() with a TLS context and setting the config `LDAP_ADD_SERVER=False`.

**Pull request closed without merging**
